#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "No version supplied"
    exit 1
fi

git tag -s -a $1 -m ''
git push --follow-tags
open 'https://github.com/kiliankoe/SwiftLibrary/releases/new'

# echo "public let APODIDAE_VERSION = \""$(git describe)"\"" > Sources/ApodidaeCore/Version.swift
swift build -c release

cd .build/release
tar -zcf swiftlibrary.tar.gz swift-library
shasum -a 256 swiftlibrary.tar.gz

open .
