#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "No version supplied"
    exit 1
fi

git tag -s -a $1 -m ''

echo "public let APODIDAE_VERSION = \""$(git describe)"\"" > Sources/ApodidaeCore/Version.swift
swift build -c release -Xswiftc -static-stdlib

cd .build/release
tar -zcf apodidae.tar.gz swift-catalog
shasum -a 256 apodidae.tar.gz

open .
